server:
 port: 8080
 
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

logging.config: classpath:log/logback-spring.xml
logging.path: /Users/wuxingya/IdeaProjects/springboot1/SpringBoot1